# Generated by Django 5.2.1 on 2025-05-26 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicosaldo',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HistoricoSaldo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transacao',
            name='categoria_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transacao', to='financeiro.categoria'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcelastransacao',
            name='transacao_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ParcelasTransacao', to='financeiro.transacao'),
        ),
    ]
