# Generated by Django 5.1.7 on 2025-03-29 21:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('r', 'receita'), ('d', 'despesa')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=13)),
                ('data_inicio', models.DateField(default=datetime.date(2025, 3, 29))),
                ('data_fim', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=100, null=True)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Metas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('r', 'receita'), ('d', 'despesa')], max_length=8)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=13)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data', models.DateField()),
                ('eh_recorrente', models.BooleanField(default=False)),
                ('recorrencia_tipo', models.CharField(choices=[('m', 'mensal'), ('t', 'trimestral'), ('a', 'anual')], default='m', max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=100, null=True)),
                ('categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categoria', to='saldo.categoria')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
