# Generated by Django 5.1.7 on 2025-03-30 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saldo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transacao', to='saldo.categoria'),
        ),
    ]
