# Generated by Django 5.2.1 on 2025-06-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_guardado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('T', 'Atrasado'), ('P', 'Pausado'), ('C', 'Concluido')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Deposito'), ('R', 'Resgate')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
