# Generated by Django 5.2.1 on 2025-05-18 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sub_categoria', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('R', 'D')], max_length=1)),
                ('quantidade_parcelas', models.IntegerField(default=1)),
                ('descricao', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelasTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ordem_parcela', models.PositiveIntegerField()),
                ('pago', models.BooleanField(default=True)),
                ('categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ParcelasTransacao', to='financeiro.categoria')),
            ],
        ),
    ]
