# Generated by Django 5.1.7 on 2025-03-20 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='user',
            new_name='fk_user',
        ),
    ]
