# Generated by Django 5.2.1 on 2025-05-28 00:01

import apps.usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', apps.usuarios.models.CustomUserManager()),
            ],
        ),
    ]
