# Generated by Django 5.2.1 on 2025-07-20 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_customuser_dataultimatransacaoverificada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dataUltimaTransacaoVerificada',
            field=models.DateField(default=datetime.datetime(2025, 7, 20, 10, 58, 14, 433975, tzinfo=datetime.timezone.utc)),
        ),
    ]
