# Generated by Django 5.2.1 on 2025-07-20 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_dataultimatransacaoverificada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dataUltimaTransacaoVerificada',
            field=models.DateField(default=datetime.date(2025, 7, 20)),
        ),
    ]
