# Generated by Django 5.2.1 on 2025-05-26 01:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MAX', 'Limite máximo'), ('MIN', 'Minimo desejado')], max_length=3)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('U', 'Ultrapassado'), ('N', 'Não atingido'), ('C', 'Concluido')], default='A', max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim', models.DateField()),
                ('descricao', models.CharField(max_length=100, null=True)),
                ('categoria_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Metas', to='financeiro.categoria')),
            ],
        ),
    ]
