# Generated by Django 5.2.1 on 2025-06-04 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metas',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Metas', to=settings.AUTH_USER_MODEL),
        ),
    ]
