# Generated by Django 5.2.1 on 2025-06-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metas',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
